### PR TITLE
Solving #17 initial commits for python3 support

### PR DESCRIPTION
**Pull request by njkevlani**

### CODE REVIEW

**Comment by njkevlani** [comment]
This commit adds support for python3 as mentioned in issue #17

**Comment by njkevlani** [comment]
@daxeel can you please review this PR?

**Comment by daxeel** [comment]
@njkevlani Did you check that this will work with both python versions or it will stop working with py2?

**Comment by njkevlani** [comment]
It is working with both, `python2` and `python3.` Checked both, `blockshell` and web interface.
blockshell2
blockshell1

**Comment by njkevlani** [comment]
ping @daxeel

**Comment by daxeel** [comment]
Hi @njkevlani,

Thanks for your continuous support. We are dedicatedly working on Blockshell to make it more stable and available to college students. Thing is that we are working on the development roadmap and execution roadmap to enter in CS colleges. That's why right now we are spending less time to check the PRs. 

But be patient. We are coming up with good news shortly. Meanwhile, you can develop and go forward with your own version of blockshell and you can start teaching Blockchain with Blockshell in your network. Just do let us know whatever you are doing with Blockshell because then only we will be able to provide you the best support from our side.

Hope you understand.

- Team BlockShell.

**Pull request closed without merging**
