### PR TITLE
Docker file

### PR DESCRIPTION
**Pull request by agentcobra**
Hi everybody,
I'm a docker beginner,
I'm trying to dockerize blockshell

### CODE REVIEW

**Comment by agentcobra** [comment]
#8 maybe need for my docker container :)

**Comment by smitthakkar96** [comment]
Why will someone containerize block shell since as far as I know it is only meant for learning blockchain

**Comment by agentcobra** [comment]
it's easier to install and less problem with python 2.7

**Comment by smitthakkar96** [comment]
Well in that case submit a PR that makes it python 3 compatible and upload a RPM spec to package it for fedora, do debian packaging and also homebrew. You containerize things to run it in prodution on servers this is a CLI. FYI docker is not a package manager.

**Comment by seeder** [comment]
docker ain't complicated, checkout #13

**Comment by agentcobra** [comment]
thx @seeder, I've merge it.
you can close your PR#13 because @smitthakkar96 will not approve it, see above

**Comment by daxeel** [comment]
@seeder @agentcobra It's great that you guys are putting efforts into this very young project in Blockchain field. Our next plan is to make Blockshell decentralized and then we will make it Docker compatible. So, guys, I know docker will add beauty to this project but before that, we need to add decentralization. If you can work on decentralization, then it would be super awesome thing. Hope you guys are getting me.

**Comment by seeder** [comment]
I think you are mistaking some domains here @daxeel 
Your project is already docker compatible.
Docker image is a great way to package CLI, daemons and even readme files.

I have just shared something what is dirt easy for me, as I work with docker on daily basis and I have noticed you don't.

I am happy to just leave my fork/pr for everyone who wants to just use it inside Docker. @agentcobra enjoy!

Cheerio

**Pull request closed without merging**
